import * as cdk from "aws-cdk-lib";
import * as ec2 from "aws-cdk-lib/aws-ec2";
import * as rds from "aws-cdk-lib/aws-rds";
import * as secretsmanager from "aws-cdk-lib/aws-secretsmanager";
import { Construct } from "constructs";

export interface DatabaseProps {
  readonly vpc: ec2.Vpc;
}

/**
 * Managed PostgreSQL 16 (RDS) for the app.
 *
 * - db.t4g.micro, single-AZ, 20 GB gp3 — the cost-conscious "dev size". Bump instanceType /
 *   allocatedStorage / multiAz when you have real traffic.
 * - Lives in the VPC's ISOLATED subnets: no internet route in or out. The only thing allowed
 *   to open a connection is the API's security group (wired up in the Api construct via
 *   `instance.connections.allowDefaultPortFrom(...)`).
 * - Credentials are generated by RDS into a Secrets Manager secret (never in code). The API
 *   reads the individual fields (host/user/password/...) from that secret at boot.
 * - storageEncrypted + 7-day automated backups + a final snapshot on delete.
 */
export class Database extends Construct {
  public readonly instance: rds.DatabaseInstance;
  public readonly secret: secretsmanager.ISecret;

  constructor(scope: Construct, id: string, props: DatabaseProps) {
    super(scope, id);

    this.instance = new rds.DatabaseInstance(this, "Postgres", {
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_16_4,
      }),
      vpc: props.vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_ISOLATED },
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.BURSTABLE4_GRAVITON, // t4g
        ec2.InstanceSize.MICRO
      ),
      allocatedStorage: 20,
      storageType: rds.StorageType.GP3,
      databaseName: "clubhub",
      // RDS generates the password into Secrets Manager. Exclude characters that would break a
      // URL-form DSN (the entrypoint builds postgresql+psycopg://user:pass@host/db from the parts).
      credentials: rds.Credentials.fromGeneratedSecret("clubhub", {
        excludeCharacters: "/@\"\\ %:#?&=+'`",
      }),
      storageEncrypted: true,
      multiAz: false,
      backupRetention: cdk.Duration.days(7),
      deletionProtection: false, // set true once this holds data you can't lose
      removalPolicy: cdk.RemovalPolicy.SNAPSHOT, // snapshot on stack delete, don't silently drop
    });

    // `.secret` is the RDS-attached secret: { username, password, host, port, dbname, ... }.
    this.secret = this.instance.secret!;
  }
}
