"""college_requests table

Revision ID: 0096ed622e47
Revises: 22dca534e69f
Create Date: 2026-07-20 15:52:54.134236

Logs colleges users couldn't find in the curated CollegeSelect picker (frontend
src/data/collegesIndia.ts) so they can be reviewed and added later.
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # autogenerated migrations reference sqlmodel.sql.sqltypes.* — must be imported

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0096ed622e47"
down_revision: str | None = "22dca534e69f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "college_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("requested_by", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("college_requests")
