"""add promotion notices

Revision ID: 0b30cc8832b2
Revises: f2a7c4e91b3d
Create Date: 2026-09-06 09:39:23.677394

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # autogenerated migrations reference sqlmodel.sql.sqltypes.* — must be imported

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0b30cc8832b2'
down_revision: str | None = 'f2a7c4e91b3d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion_notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('club_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('new_role', sa.String(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_promotion_notices_user', 'promotion_notices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_promotion_notices_user', table_name='promotion_notices')
    op.drop_table('promotion_notices')
    # ### end Alembic commands ###
