"""college promotion tables

Revision ID: 4f79ce740388
Revises: e56859779389
Create Date: 2026-09-13 16:19:49.319803

Closes the loop on college_requests (0096ed622e47): `college_request_supporters` records one
row per distinct user backing a pending request (uq_college_request_supporter, mirroring
event_rsvps' idempotency pattern), and `colleges` is the public, auto-promoted list a request
graduates into once it clears the distinct-requester threshold — see
app/scripts/promote_college_requests.py and app/core/config.py's COLLEGE_PROMOTION_* settings.
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # autogenerated migrations reference sqlmodel.sql.sqltypes.* — must be imported

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f79ce740388"
down_revision: str | None = "e56859779389"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "college_request_supporters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("college_request_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["college_request_id"], ["college_requests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("college_request_id", "user_id", name="uq_college_request_supporter"),
    )
    op.create_table(
        "colleges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_request_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["source_request_id"], ["college_requests.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("colleges")
    op.drop_table("college_request_supporters")
