"""refresh tokens and event rsvps

Revision ID: d19c5a7b8e02
Revises: b7f3c1a9d2e4
Create Date: 2026-07-03 00:00:00.000000

Adds the two tables for the auth-refresh flow and event RSVPs, plus the events
(club_id, status) listing index. Hand-written: FK ondelete rules are set at creation
(autogenerate does not diff them — see b7f3c1a9d2e4), following the established matrix:
club_id / participation rows -> CASCADE.
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # autogenerated migrations reference sqlmodel.sql.sqltypes.* — must be imported

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d19c5a7b8e02"
down_revision: str | None = "b7f3c1a9d2e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )

    op.create_table(
        "event_rsvps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "user_id", name="uq_event_rsvp"),
    )
    op.create_index(op.f("ix_event_rsvps_club_id"), "event_rsvps", ["club_id"], unique=False)

    op.create_index("ix_events_club_status", "events", ["club_id", "status"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_events_club_status", table_name="events")
    op.drop_index(op.f("ix_event_rsvps_club_id"), table_name="event_rsvps")
    op.drop_table("event_rsvps")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
