"""users country and state

Revision ID: e4a1f6c9d371
Revises: d19c5a7b8e02
Create Date: 2026-07-04 00:00:00.000000

Adds the two location profile columns collected by the redesigned registration flow.
Nullable VARCHAR (free-form display strings from the frontend's country/state picker) —
plain strings per ADR-0001, validated at the API edge.
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # autogenerated migrations reference sqlmodel.sql.sqltypes.* — must be imported

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4a1f6c9d371"
down_revision: str | None = "d19c5a7b8e02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("users", sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("users", sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True))


def downgrade() -> None:
    op.drop_column("users", "state")
    op.drop_column("users", "country")
