import { WORDMARK_SIZE, WORDMARK_SRC, WORDMARK_SRCSET } from "./wordmarkAssets";

interface WordmarkProps {
  /** Rendered width. The mark scales from this — height follows the aspect. */
  className?: string;
  /**
   * Hint for which rendition the browser fetches. Set it to the CSS width the
   * mark is drawn at; the default suits the 150–185px header and footer slots.
   */
  sizes?: string;
  title?: string;
}

/**
 * The ClubHub wordmark: red and black cut-paper letters, each on its own
 * cream scrap with a torn edge, flanked by a few burst marks.
 *
 * Mirrored by landing/src/features/newspaper/Wordmark.tsx. The renditions in
 * public/brand/ and `wordmarkAssets.ts` are generated by scripts/gen-wordmark.mjs
 * for both apps at once — regenerate, never hand-edit.
 *
 * It is an image, not outlines, because the artwork is full-colour, paper-textured
 * and torn-edged; see the generator for why the old two-colour trace could not
 * survive that. The width/height attributes reserve the box from the
 * intrinsic aspect, so the page does not shift when the file arrives, and the
 * letters carry their own cream border, which is what lets the same mark sit on
 * the ink footers without a recoloured variant.
 */
export function Wordmark({ className = "", sizes = "190px", title = "ClubHub" }: WordmarkProps) {
  return (
    // eslint-disable-next-line @next/next/no-img-element -- art is pre-sized by gen-wordmark; the optimizer would re-encode it
    <img
      src={WORDMARK_SRC}
      srcSet={WORDMARK_SRCSET}
      sizes={sizes}
      width={WORDMARK_SIZE.w}
      height={WORDMARK_SIZE.h}
      alt={title}
      className={`wired-wordmark ${className}`}
      draggable={false}
    />
  );
}
