import { WORDMARK_SIZE, WORDMARK_SRC, WORDMARK_SRCSET } from "./wordmarkAssets";

interface WordmarkProps {
  /** Rendered width. The mark scales from this — height follows the aspect. */
  className?: string;
  /**
   * Hint for which rendition the browser fetches. Set it to the CSS width the
   * mark is drawn at.
   */
  sizes?: string;
  /** Marks the nameplate as the page's LCP image so it is fetched first. */
  priority?: boolean;
  title?: string;
}

/**
 * The ClubHub wordmark: red and black cut-paper letters, each on its own
 * cream scrap with a torn edge, flanked by a few burst marks.
 *
 * Mirrors frontend/src/components/ui/Wordmark.tsx. The renditions in
 * public/brand/ and `wordmarkAssets.ts` are generated by scripts/gen-wordmark.mjs
 * for both apps at once — regenerate, never hand-edit.
 *
 * It is an image, not outlines, because the artwork is full-colour, paper-textured
 * and torn-edged; see the generator for why the old two-colour trace could not
 * survive that. The width/height attributes reserve the box from the
 * intrinsic aspect, so the page does not shift when the file arrives. On the
 * nameplate — the largest thing on page one — `priority` lifts it to the front
 * of the fetch queue, since that is the one place it is the LCP element.
 */
export default function Wordmark({
  className = "",
  sizes = "190px",
  priority = false,
  title = "ClubHub",
}: WordmarkProps) {
  return (
    // eslint-disable-next-line @next/next/no-img-element -- static export, images.unoptimized; art is pre-sized by gen-wordmark
    <img
      src={WORDMARK_SRC}
      srcSet={WORDMARK_SRCSET}
      sizes={sizes}
      width={WORDMARK_SIZE.w}
      height={WORDMARK_SIZE.h}
      alt={title}
      className={`np-wordmark ${className}`}
      fetchPriority={priority ? "high" : undefined}
      draggable={false}
    />
  );
}
